### ISSUE TITLE
分手的时候报错 帮忙看一下是怎么了

### ISSUE THREAD

**Issue by 3455315719** [Rs794613/PcrDuel#6]
![R7A{Q%XZMUEJD6JO}F8OW9D](https://user-images.githubusercontent.com/68584989/106440053-5a30c000-64b3-11eb-9f6f-58affc437f9c.png)

**Comment by Rs794613** [comment]
图我点不开，如果是决斗中分手的话，那个判断应该写在gid声明后面，之后我改一下。

**Comment by 3455315719** [comment]
[2021-02-01 17:29:58,637 nonebot] INFO: Message 350433899 is ignored
[2021-02-01 17:30:05,312 nonebot] INFO: Self: 1729307885, Message -212131988 from 3455315719@[群:652180717]: '分手空花'
[2021-02-01 17:30:05,327 pcr-duel] INFO: Message -212131988 triggered breakup by PrefixTrigger.
[2021-02-01 17:30:05,327 pcr-duel] ERROR: <class 'UnboundLocalError'> occured when breakup handling message -212131988.
[2021-02-01 17:30:05,327 pcr-duel] ERROR: local variable 'gid' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\pcr\HoshinoBot\hoshino\msghandler.py", line 28, in handle_message
    await sf.func(bot, event)
  File "C:\Users\Administrator\Desktop\pcr\HoshinoBot\hoshino\modules\priconne\pcr_duel\__init__.py", line 1552, in brea
kup
    if duel_judger.get_on_off_accept_status(gid):
UnboundLocalError: local variable 'gid' referenced before assignment

**Comment by Rs794613** [comment]
就是我说的那个，刚才更新的init文件里已经修复了。
