### ISSUE TITLE
更新以后的插件不能加载了 

### ISSUE THREAD

**Issue by 3455315719** [Rs794613/PcrDuel#7]
[2021-02-01 18:43:05,923 nonebot] ERROR: Failed to import "hoshino.modules.prico
nne.pcr_duel", error: expected an indented block (__init__.py, line 1563)
[2021-02-01 18:43:05,923 nonebot] ERROR: expected an indented block (__init__.py
, line 1563)
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\nonebot\plugin.py", line 249, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\import
lib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\pcr\HoshinoBot\hoshino\modules\priconne\p
cr_duel\__init__.py", line 1563
    msg = '现在正在决斗中哦，请决斗后再来谈分手事宜吧。'
    ^
IndentationError: expected an indented block

**Comment by Rs794613** [comment]
有一处缩进错了，现在好了。

**Comment by 3455315719** [comment]
十分感谢
